---
version: "3"
services:
 devopsdb:
   
   image: pavan1097/mynewapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: pavan1097/mynewapp:appimage
 
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
